name: Xray cucumber export
description: Export Xray Cucumber feature files

inputs:
  client_id:
    required: true
  client_secret:
    required: true
  filter:
    required: false
    default: ''
  keys:
    required: false
    default: ''
  destination_dir:
    required: true

runs:
  using: "composite"
  steps:
    - name: Step1 - Xray authentication using token
      id: xray-token
      shell: bash
      run: |
        echo ::set-output name=XRAY_TOKEN::$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\":\"${{ inputs.client_id }}\",\"client_secret\":\"${{ inputs.client_secret }}\" }" https://xray.cloud.getxray.app/api/v1/authenticate | tr -d '"')
  
    - name: Step2 - Get Feature Files(Test Cases) from Xray
      shell: bash
      run: 'curl -H "Content-Type: application/json" --output $RUNNER_TEMP/features.zip -X GET -H "Authorization: Bearer ${{ steps.xray-token.outputs.XRAY_TOKEN }}" "https://xray.cloud.getxray.app/api/v2/export/cucumber?filter=${{ inputs.filter }}&keys=${{ inputs.keys }}"'

    - name: Step3 - Unzip the feature files(Test Cases)
      shell: bash
      run: unzip -o $RUNNER_TEMP/features.zip
      working-directory: ${{ inputs.destination_dir }}
